[project]
name = "stt"
version = "0.1.0"
description = "Speech-to-text microservice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ 
    "fastapi[standard]>=0.115.12",
    "gigaam @ git+https://github.com/salute-developers/GigaAM.git",
]
